### ISSUE TITLE
Error in scheduled weekly tests for py313

### ISSUE THREAD

**Issue by heevasti** [QuTech-Delft/QMI#118]
Description
========

The scheduled weekly pipelines gave an error on the Python 3.13 unit-tests. The `py-xdrlib` did not get correctly installed. The problem is likely in the if statement:
```yaml
      - name: Run unit tests and generate report
        if: always()
        run: |
          if [[ ${{ matrix.python-version }} == "3.13" ]]; \
            then pip install https://github.com/da4089/py-xdrlib/archive/refs/heads/main.zip; fi
          pip install .
          pip install unittest-xml-reporting
          python -m xmlrunner --output-file testresults.xml discover --start-directory=tests --pattern="test_*.py"
```

It should get fixed by moving the statement in its owe section, something like this:
```yaml
      - name: Check py-xdrlib installation for Python 3.13
        if: [[ ${{ matrix.python-version }} == "3.13" ]]
        run:
            pip install https://github.com/da4089/py-xdrlib/archive/refs/heads/main.zip

      - name: Run unit tests and generate report
        if: always()
        run:
          ...
```

ps. We could possibly wait for the [`py-xdrlib` 4.0.2 release](https://github.com/da4089/py-xdrlib/issues/3), so that we can do simply `pip install py-xdrlib` instead of providing the while Github hubbub.

Affected components
------------------------
CI weekly scheduled pipelines

Modules to be modified
---------------------------
- `.github/workflows/scheduled-full-ci.yml`

Documentation
-----------------
No need to edit CHANGELOG.md just for this.
